name: Build Tweak

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y git fakeroot make perl clang dpkg dpkg-dev libssl-dev libplist-dev libplist++-dev lzma-dev

    - name: Install Theos
      run: |
        git clone --recursive https://github.com/theos/theos.git $HOME/theos
        echo "THEOS=$HOME/theos" >> $GITHUB_ENV

    - name: Install ldid (prebuilt)
      run: |
        wget https://apt.procurs.us/pool/main/l/ldid/ldid_2.1.5-procursus7_amd64.deb
        sudo dpkg -i ldid_2.1.5-procursus7_amd64.deb

    - name: Build tweak
      run: |
        make clean package FINALPACKAGE=1
      env:
        THEOS: ${{ env.THEOS }}

    - name: Upload .deb package
      uses: actions/upload-artifact@v4
      with:
        name: tweak-package
        path: ./packages/*.deb
